### ISSUE TITLE
0.3.0 causes errors while 0.2.4 works without trouble

### ISSUE THREAD

**Issue by An0therOne** [Goby56/wakes#113] opened 2024-10-20 18:13 UTC
**Describe the bug**
When using wakes 0.3.0 the wakes just... don't appear, and instead blocks of water just turn black. Though rain drops on water does work as normal. Not only that, but exiting the world also crashes the game, and I figured out this is because of this version of wakes, how? I downgraded to 0.2.4 and it works just fine, wakes and everything, and the crashing when leaving the world doesn't happen, therefore it is 0.3.0's fault.

**Expected behavior**
For wakes to work normally.
For the game to not crash when leaving world.

**To Reproduce**
1. Load World.
2. Water doesn't work fully as intended.
3. Leave World.
4. While saving, Minecraft crashes.

**Screenshots**
![2024-10-20_12 06 29](https://github.com/user-attachments/assets/5bd70d8e-df26-4ce1-a90b-1ab87dcd055f)
![2024-10-20_12 06 42](https://github.com/user-attachments/assets/d6e120c3-25b9-4dbd-aef2-75f20d15dd77)
![Screenshot_123](https://github.com/user-attachments/assets/55310789-7d06-4d14-a5a8-9991f1d43abc)
![Screenshot_124](https://github.com/user-attachments/assets/8ffc0ca9-aa0e-46af-8838-81d1c60540a4)

**Hardware and OS**
AMD Ryzen 3 3200G with Radeon Vega Graphics 3.60 GHz
Windows 10.0.19045.5011

**Versions**
- 1.20.1
- Fabric 0.16.7
- Wakes 0.3.0
- Fabric API 0.92.2

**Additional information**
https://mclo.gs/b3c38Wu

**Comment by Arach-Knight** [comment] 2024-11-09 19:12
Same issue here

Im using quilt modloader 0.27.0 beta
mc version 1.20.1
Quilt API 7.6.0
Yacl 3.6.1

One time it happened to me that it didnt crash upon exiting the world, but then upon reentry it did crash, and thus i was locked out of that world until i downgraded Wakes.

**Comment by Goby56** [comment] 2024-12-29 17:43
Duplicate of #102

**Closed by Goby56** 2024-12-29 17:43 UTC
Labels: bug
