### ISSUE TITLE
Effects stay on surface after the entity is dead.

### ISSUE THREAD

**Issue by Albaraa-PC** [Goby56/wakes#58] opened 2024-02-27 07:10 UTC
Every time I kill any mob on the water it's effect stay on the surface. This bug wasn't there in old versions of the mod.

Minecraft version: 1.20.1
Mod version: Fabric 0.15.7, iris 1.6.17.
Wakes version: 0.2.3
Fabric API: 0.92.0+1.20.1
![Base Profile Screenshot 2024 02 23 - 17 09 16 45](https://github.com/Goby56/wakes/assets/131908238/c6e4fe92-e5be-4d82-853e-668388c16368)

**Comment by Goby56** [comment] 2024-04-03 11:01
Duplicate of #35

**Closed by Goby56** 2024-04-03 11:01 UTC
Labels: bug
