### ISSUE TITLE
Water under wakes keep disappearing

### ISSUE THREAD

**Issue by Terrorstrike129** [Goby56/wakes#27] opened 2023-11-13 02:35 UTC
I've tried using every debug feature I can think of, and no matter what the highlighted debug tiles always disappear in-game.
![image](https://github.com/Goby56/wakes/assets/138547132/0270920b-91a7-4576-8677-195f0488840b)

**Comment by Goby56** [comment] 2023-11-13 06:27
Do you have fabulous graphics settings turned on?

**Comment by Terrorstrike129** [comment] 2023-11-13 12:28
I think
________________________________

**Comment by Goby56** [comment] 2023-11-13 16:05
Well try turning it off and see if the bug remains. If you can see the water with either fancy or fast graphics on this is most likely a duplicate of #22.

**Closed** 2023-12-20 19:27 UTC
Labels: bug
