### ISSUE TITLE
Wakes 0.3.0+1.20.1 crashing when exiting the world

### ISSUE THREAD

**Issue by greyxp1** [Goby56/wakes#112] opened 2024-10-09 22:26 UTC
Game sometimes crashes when you quit a world. Downgraded to Wakes 0.2.4+1.20.1 and issue was fixed.

Log:

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_638.method_8316(net.minecraft.class_2338)" because "net.minecraft.class_310.method_1551().field_1687" is null
	at com.goby56.wakes.simulation.WakeNode.validPos(WakeNode.java:199)
	at com.goby56.wakes.simulation.WakeHandler.insert(WakeHandler.java:76)
	at com.goby56.wakes.utils.WakesUtils.placeWakeTrail(WakesUtils.java:95)

**Comment by JamesMinoucha** [comment] 2024-10-11 11:33
Me too, when rejoining the world :
```
---- Minecraft Crash Report ----
// There are four lights!

Time: 2024-10-11 13:29:04
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_638.method_8316(net.minecraft.class_2338)" because "net.minecraft.class_310.method_1551().field_1687" is null
	at com.goby56.wakes.simulation.WakeNode.validPos(WakeNode.java:199)
	at com.goby56.wakes.simulation.WakeHandler.insert(WakeHandler.java:76)
	at com.goby56.wakes.utils.WakesUtils.placeWakeTrail(WakesUtils.java:95)
	at net.minecraft.class_1297.spawnEffects(class_1297.java:17447)
	at net.minecraft.class_1297.handler$dnf006$wakes$tick(class_1297.java:17418)
	at net.minecraft.class_1297.method_5773(class_1297.java:475)
	at net.minecraft.class_1690.method_5773(class_1690.java:280)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.goby56.wakes.simulation.WakeNode.validPos(WakeNode.java:199)
	at com.goby56.wakes.simulation.WakeHandler.insert(WakeHandler.java:76)
	at com.goby56.wakes.utils.WakesUtils.placeWakeTrail(WakesUtils.java:95)
	at net.minecraft.class_1297.spawnEffects(class_1297.java:17447)
	at net.minecraft.class_1297.handler$dnf006$wakes$tick(class_1297.java:17418)
	at net.minecraft.class_1297.method_5773(class_1297.java:475)
	at net.minecraft.class_1690.method_5773(class_1690.java:280)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)

-- Entity being ticked --
Details:
	Entity Type: minecraft:boat (net.minecraft.class_1690)
	Entity ID: 1045
	Entity Name: Boat
	Entity's Exact location: 158.65, 62.52, -70.46
	Entity's Block location: World: (158,62,-71), Section: (at 14,14,9 in 9,3,-5; chunk contains blocks 144,-64,-80 to 159,319,-65), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: [class_7102['Frog'/1046, l='ServerLevel[Test World 2]', x=159.03, y=62.56, z=-70.58], class_7102['Frog'/1047, l='ServerLevel[Test World 2]', x=158.27, y=62.56, z=-70.33]]
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by NerdSkape** [comment] 2024-10-12 15:26
I'm also having this issue in 1.21. Everything was fine until a couple of days ago so I suspect that this is a conflict with another mod since Wakes hasn't been updated in a while.

I was able to resolve the conflict two different ways. It seems Wakes experiences this crash when using the Concentration mod to play with a borderless window so disabling the Concentration mod prevented the crash for me. I experimented with Concentration since it was one of my mods that were recently updated.

This wasn't an ideal solution since I don't want to play full screen so I started testing different settings in Wakes. My testing has been limited, but so far under Basic Settings changing Mobs to any values that doesn't use simulation prevents the crash. I am currently playing with it set to Only Plane and haven't had any further issues so far.

**Comment by airon-main** [comment] 2024-10-19 22:10
been testing with removing some world generation mod. dungeon and tavern is the culprit, disabled it and no longer crashes and my fps increased twice

**Comment by airon-main** [comment] 2024-10-19 22:25
wait nvm. encountered the crash again

**Comment by airon-main** [comment] 2024-10-19 22:45
> I'm also having this issue in 1.21. Everything was fine until a couple of days ago so I suspect that this is a conflict with another mod since Wakes hasn't been updated in a while.
> 
> I was able to resolve the conflict two different ways. It seems Wakes experiences this crash when using the Concentration mod to play with a borderless window so disabling the Concentration mod prevented the crash for me. I experimented with Concentration since it was one of my mods that were recently updated.
> 
> This wasn't an ideal solution since I don't want to play full screen so I started testing different settings in Wakes. My testing has been limited, but so far under Basic Settings changing Mobs to any values that doesn't use simulation prevents the crash. I am currently playing with it set to Only Plane and haven't had any further issues so far.

wierd, i tested by removing cube without border (borderless mod) and i still encounter the crash

**Comment by KingContaria** [comment] 2024-10-23 18:09
Hi, im the developer of FastQuit and this is a compatibility issue between FastQuit and Wakes.
Its caused by FastQuit letting the integrated server save in the background, which causes it to be active at a time where no client world exists anymore.
Wakes calls some of its functions that access the clientworld in the entity tick function, both on the client and the server thread. Im not too familiar with this mod so idk if these calls on the server thread are intentional, if they aren't you could simply add a `world.isClient` check, if they are intentional i think the fix in https://github.com/Goby56/wakes/commit/b0a0b3bdde5d5fe020b7dfaa471bdbfa27c0744c should also work to resolve this issue

**Comment by Goby56** [comment] 2024-12-29 17:41
Duplicate of #102

**Closed** 2024-12-29 17:45 UTC
Labels: bug, crash
