### ISSUE TITLE
Crash when tamed pet teleports to player

### ISSUE THREAD

**Issue by Woelfiger** [Goby56/wakes#104] opened 2024-09-04 19:42 UTC
i am getting this 

Caused by: java.lang.ClassCastException: class com.cobblemon.mod.common.entity.pokemon.ai.goals.PokemonFollowOwnerGoal cannot be cast to class com.goby56.wakes.duck.ProducesWake (com.cobblemon.mod.common.entity.pokemon.ai.goals.PokemonFollowOwnerGoal and com.goby56.wakes.duck.ProducesWake are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @55040f2f) 

in my log after i go with a me following pokemon near water first nothing happens its a little laggie till it somtimes randomly crashes.

here my crashreport i hope it helps and you can fix the issue i lofe this mod

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2024-09-04 21:22:13
Description: Ticking entity

java.lang.ClassCastException: class com.cobblemon.mod.common.entity.pokemon.ai.goals.PokemonFollowOwnerGoal cannot be cast to class com.goby56.wakes.duck.ProducesWake (com.cobblemon.mod.common.entity.pokemon.ai.goals.PokemonFollowOwnerGoal and com.goby56.wakes.duck.ProducesWake are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @55040f2f)
	at net.minecraft.class_1350.handler$heh000$wakes$onTeleport(class_1350.java:1017)
	at net.minecraft.class_1350.method_23343(class_1350.java:143)
	at net.minecraft.class_1350.method_23345(class_1350.java:126)
	at net.minecraft.class_1350.method_6268(class_1350.java:113)
	at net.minecraft.class_4135.method_6268(class_4135.java:65)
	at net.minecraft.class_1355.method_38849(class_1355.java:120)
	at net.minecraft.class_1355.method_6275(class_1355.java:111)
	at net.minecraft.class_1308.method_6023(class_1308.java:771)
	at net.minecraft.class_1309.method_6007(class_1309.java:2673)
	at net.minecraft.class_1308.method_6007(class_1308.java:550)
	at net.minecraft.class_1296.method_6007(class_1296.java:128)
	at net.minecraft.class_1429.method_6007(class_1429.java:58)
	at net.minecraft.class_1309.method_5773(class_1309.java:2419)
	at net.minecraft.class_1308.method_5773(class_1308.java:351)
	at net.minecraft.class_1471.method_5773(class_1471.java:35)
	at com.cobblemon.mod.common.entity.pokemon.PokemonEntity.method_5773(PokemonEntity.java:313)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1350.handler$heh000$wakes$onTeleport(class_1350.java:1017)
	at net.minecraft.class_1350.method_23343(class_1350.java:143)
	at net.minecraft.class_1350.method_23345(class_1350.java:126)
	at net.minecraft.class_1350.method_6268(class_1350.java:113)
	at net.minecraft.class_4135.method_6268(class_4135.java:65)
	at net.minecraft.class_1355.method_38849(class_1355.java:120)
	at net.minecraft.class_1355.method_6275(class_1355.java:111)
	at net.minecraft.class_1308.method_6023(class_1308.java:771)
	at net.minecraft.class_1309.method_6007(class_1309.java:2673)
	at net.minecraft.class_1308.method_6007(class_1308.java:550)
	at net.minecraft.class_1296.method_6007(class_1296.java:128)
	at net.minecraft.class_1429.method_6007(class_1429.java:58)
	at net.minecraft.class_1309.method_5773(class_1309.java:2419)
	at net.minecraft.class_1308.method_5773(class_1308.java:351)
	at net.minecraft.class_1471.method_5773(class_1471.java:35)
	at com.cobblemon.mod.common.entity.pokemon.PokemonEntity.method_5773(PokemonEntity.java:313)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)

-- Entity being ticked --
Details:
	Entity Type: cobblemon:pokemon (com.cobblemon.mod.common.entity.pokemon.PokemonEntity)
	Entity ID: 716
	Entity Name: Swellow
	Entity's Exact location: -5.50, 64.00, 54.50
	Entity's Block location: World: (-6,64,54), Section: (at 10,0,6 in -1,4,3; chunk contains blocks -16,-64,48 to -1,319,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Entity's Momentum: 0.13, 0.00, -0.14
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Woelfiger'/2, l='ServerLevel[Cobbled Farms]', x=-6.85, y=64.20, z=57.45]]
	Chunk stats: 4830
	Level dimension: minecraft:overworld
	Level spawn location: World: (-2,85,790), Section: (at 14,5,6 in -1,5,49; chunk contains blocks -16,-64,784 to -1,319,799), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,-64,512 to -1,319,1023)
	Level time: 335728818 game time, 65629 day time
	Level name: Cobbled Farms
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Known server brands: forge, Paper, fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Cobblemon --
Details:
	Version: 1.5.2
	Is Snapshot: false
	Git Commit: df8f078 (https://gitlab.com/cable-mc/cobblemon/-/commit/df8f078d13702ab9a000438910b822ceffbb2248)
	Branch: HEAD

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 4111554592 bytes (3921 MiB) / 6442450944 bytes (6144 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD FX(tm)-8350 Eight-Core Processor           
	Identifier: AuthenticAMD Family 21 Model 2 Stepping 0
	Microarchitecture: Piledriver
	Frequency (GHz): 4.02
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 980 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x17c8
	Graphics card #0 versionInfo: DriverVersion=32.0.15.6094
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 0.67
	Memory slot #0 type: Other
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 0.67
	Memory slot #1 type: Other
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 0.67
	Memory slot #2 type: Other
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 0.67
	Memory slot #3 type: Other
	Virtual memory max (MB): 43089.48
	Virtual memory used (MB): 38608.99
	Swap memory total (MB): 18531.37
	Swap memory used (MB): 1623.04
	JVM Flags: 9 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms6144m -Xmx6144m
	Fabric Mods: 
		advancementinfo: AdvancementInfo 1.20-fabric0.83.0-1.4
		animatica: Animatica 0.6+1.20
		appleskin: AppleSkin 2.5.1+mc1.20
		architectury: Architectury 9.2.14
		armoroftheages: Armor of the Ages 1.2.3
		balm-fabric: Balm 7.2.2
		bedrockify: BedrockIfy 1.9.1+mc1.20
			panorama_screens: Panorama Screens 1.0+fabric+mc1.20
		better_end_sky: Better End Sky 0.2.1+1.20
		betterpingdisplay: Better Ping Display 1.1.1
		betterthirdperson: Better Third Person 1.9.0
		bookshelf: Bookshelf 20.1.10
		borderlessmining: Borderless Mining 1.1.8+1.20.1
		bwncr: Bad Wither No Cookie Reloaded 3.17.0
		carryon: Carry On 2.1.2.7
		cavedust: Cave Dust 1.4.1
		cherishedworlds: Cherished Worlds 6.1.6+1.20.1
		chesttracker: Chest Tracker 1.1.23
			whereisit: Where Is It 1.14.17
		cicada: CICADA 0.7.1+1.20.1
		cleancut: CleanCut 6.0+mc1.19.1-mc1.20.x
		cleardespawn: Clear Despawn 1.1.15
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 12.0.0.4
		cobbled-shiny-particles: Cobbled Shiny Particles 1.0.6.1
		cobbledex: Cobbledex 1.1.0
		cobblefoods: CobbleFoods 1.2-1.20.1
		cobblemizer: Cobblemon Customizer for Fabric 2.0.1
		cobblemon: Cobblemon 1.5.2+1.20.1
		cobblemon-ui-tweaks: Cobblemon UI Tweaks 1.0.6
		cobblemon_capturexp: Cobblemon Capture EXP 1.5-fabric-1.0.1
		cobblemon_chaining: Cobblemon Chaining 1.5-fabric-1.0.1
		cobblemon_counter: Cobblemon Counter 1.5-fabric-1.2.0
		cobblemon_move_inspector: Cobblemon Move Inspector 1.1.1
		cobblemon_spawn_notification: Cobblemon Spawn Notification 1.5-fabric-1.0.0
		cobblemon_unimplementeditems: Cobblemon Unimplemented Items 1.5-fabric-1.2.0
		cobblemonaudioaddon: Pokémon Audio Enhancer 1.1
		cobblemonbreakouts: Cobblemon Outbreaks fabric-1.1.4-1.20.1
		cobblemonintegrations: Cobblemon Integrations 1.0.6
		cobblemonmikeskills: cobblemonmikeskills 1.0.1+1.20.1
		cobblemonridingfabric: Cobblemon Riding Fabric 1.2.5
		cobblemontrainers: CobblemonTrainers 1.1.11+1.5.2
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
		cobblenav: Cobblenav 1.3.5
		cobblepedia: Cobblepedia 0.6.6
		cobbreeding: Cobbreeding 1.7.2
		collective: Collective 7.57
		continuity: Continuity 3.0.0-beta.5+1.20.1
		craftingtweaks: Crafting Tweaks 18.2.3
		craftpresence: CraftPresence 2.3.9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
		create: Create 0.5.1-f-build.1417+mc1.20.1
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.10-2
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.3.2+1.20.1
			porting_lib_base: Porting Lib Base 2.3.2+1.20.1
				porting_lib_config: Porting Lib Config 2.3.2+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.2+1.20.1
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.2+1.20.1
				porting_lib_utility: Porting Lib Utility 2.3.2+1.20.1
			porting_lib_brewing: Porting Lib Brewing 2.3.2+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.2+1.20.1
			porting_lib_entity: Porting Lib Entity 2.3.2+1.20.1
				porting_lib_core: Porting Lib Core 2.3.2+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.2+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.2+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.2+1.20.1
				porting_lib_common: Porting Lib Common 2.3.2+1.20.1
			porting_lib_models: Porting Lib Models 2.3.2+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.2+1.20.1
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.2+1.20.1
				porting_lib_model_loader: Porting Lib Model Loader 2.3.2+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.2+1.20.1
			porting_lib_transfer: Porting Lib Transfer 2.3.2+1.20.1
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_gametest: Porting Lib GameTest 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		create_cobblemon: Create: Cobblemon Industrialized 0.4
		ctrl-q: Ctrl Q 1.9
		cull-less-leaves: Cull Less Leaves 1.3.0
		dismountentity: Dismount Entity 3.2
		dynamic_fps: Dynamic FPS 3.4.3
		enchdesc: EnchantmentDescriptions 17.0.14
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.4+1.20
		entity_model_features: Entity Model Features 2.2.3
		entity_texture_features: Entity Texture Features 6.2.2
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20.1
		explosiveenhancement: Explosive Enhancement 1.2.2-1.20.x
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.10.20+kotlin.1.9.24
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.24
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.24
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.24
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.24
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		fallingleaves: Falling Leaves 1.15.6
		fancymenu: FancyMenu 3.2.2
			com_github_keksuccino_japng: japng 0.5.3
			com_github_rtyley_animated-gif-lib-for-java: animated-gif-lib-for-java animated-gif-lib-1.7
		farmersdelight: Farmer's Delight 1.20.1-1.4.3
		faster_entity_animations: FastAnim 1.6
		ferritecore: FerriteCore 6.0.1
		feytweaks: FeyTweaks 1.20-1.2.7
			midnightlib: MidnightLib 1.4.1
		forgeconfigapiport: Forge Config API Port 8.0.0
		helditemsaver: HeldItemSaver 1.0.0
		highlighter: Highlighter 1.1.9
		huliszcrystals: HuilsZCrystals 1.1
			polymer-blocks: Polymer (Textured Blocks) 0.5.18+1.20.1
			polymer-core: Polymer (Core) 0.5.18+1.20.1
				polymer-networking: Polymer (Networking) 0.5.18+1.20.1
				polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.5.18+1.20.1
			polymer-resource-pack: Polymer (Resource Pack) 0.5.18+1.20.1
				polymer-common: Polymer (Common) 0.5.18+1.20.1
					packet_tweaker: Packet Tweaker 0.4.0+1.19.4
			polymer-virtual-entity: Polymer (Virtual Entity) 0.5.18+1.20.1
		iceberg: Iceberg 1.1.18
		immediatelyfast: ImmediatelyFast 1.2.14+1.20.4
			net_lenni0451_reflect: Reflect 1.3.2
		indium: Indium 1.0.34+mc1.20.1
		invmove: InvMove 0.8.4
		iris: Iris 1.7.2+mc1.20.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		itemalchemy: Item Alchemy 0.9.0
		java: OpenJDK 64-Bit Server VM 17
		konkrete: Konkrete 1.8.1
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		ksyxis: Ksyxis 1.1
		lambdynlights: LambDynamicLights 2.3.2+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
			spruceui: SpruceUI 5.0.0+1.20
		languagereload: Language Reload 1.5.10+1.20.1
		lazydfu: LazyDFU 0.1.3
		letmedespawn: Let Me Despawn 1.2.0
		linkedstorage: Linked Storage 1.5.2-1.19.3
		lithium: Lithium 0.11.2
		longerchathistory: Longer Chat History 1.4
		lootballs: Cobblemon Loot Balls 1.1.4
		macos_input_fixes: MacOS Input Fixes 1.6
		make_bubbles_pop: Make Bubbles Pop Mod 0.2.0-fabric
		mcpitanlib: MCPitanLib 2.3.5-1.20.1-fabric
			org_yaml_snakeyaml: snakeyaml 2.0
		megamons: Ascension Megamons 1.5.0+1.20.1-forge+fabric-75b66fa
		melody: Melody 1.0.3
		memoryleakfix: Memory Leak Fix 1.1.5
		minecraft: Minecraft 1.20.1
		modmenu: Mod Menu 7.2.2
		monsters_in_the_closet: Monsters in the Closet 1.0.3+1.20
		more_cobblemon_tweaks: MoreCobblemonTweaks 0.5.1
		moreculling: More Culling 1.20.4-0.24.0
			conditional-mixin: conditional mixin 0.3.2
			mixinsquared: MixinSquared 0.1.1
		mr_cobblemon_legendarystructures: Cobblemon: Legendary Structures 1.1.1
		mythsandlegends: Myths and Legends 1.5-HOTFIX
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		naturescompass: Nature's Compass 1.20.1-2.2.3-fabric
		netherportalfix: NetherPortalFix 13.0.1
		notenoughanimations: NotEnoughAnimations 1.7.5
		notes: Notes 1.20.1-2.1.0-fabric
		nyfsspiders: Nyf's Spiders 2.1.1
		owo: oωo 0.11.2+1.20
			blue_endless_jankson: jankson 1.2.2
		particular: Particular 1.1.1
		patchouli: Patchouli 1.20.1-84-FABRIC
			fiber: fiber 0.23.0-2
		pokeplushie: pokeplushie 1.1.0
		presencefootsteps: Presence Footsteps 1.9.3
			kirin: Kirin UI 1.15.6+1.20.1
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.20.1-build.101
		roughlyenoughitems: Roughly Enough Items 12.1.725
			error_notifier: Error Notifier 1.0.9
		roughlyenoughprofessions: Roughly Enough Professions 2.0.2
		roughlysearchable: Roughly Searchable 2.6.0+1.20.1
		showmeyourskin: Show Me Your Skin! 1.9.0+1.20
			cardinal-components-base: Cardinal Components API (base) 5.2.1
			cardinal-components-entity: Cardinal Components API (entities) 5.2.1
		shulkerboxtooltip: Shulker Box Tooltip 4.0.4+1.20.1
		slimyfloor: Slimy Floor 1.20-1.2.8
		sodium: Sodium 0.5.11+mc1.20.1
		sodium-extra: Sodium Extra 0.5.4+mc1.20.1-build.115
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		sspb: Sodium Shadowy Path Blocks 3.3.0
		starlight: Starlight 1.1.2+fabric.dbc156f
		stendhal: Stendhal 1.4.1-1.20
			libgui: LibGui 8.0.1+1.20
				jankson: Jankson 5.0.1+j1.2.2
				libninepatch: LibNinePatch 1.2.0
		superflatworldnoslimes: Superflat World No Slimes 3.2
		sushi_bar: Sushi Bar 0.2.2+1.20
			com_moulberry_mixinconstraints: mixinconstraints 1.0.1
		telepistons: Telepistons 1.1.3
		titlefixer: Title Fixer 1.0+1.20.1
		tool_trims: Tool Trims 2.2.1
		toolstats: ToolStats 16.0.8
		tooltipfix: ToolTip Fix 1.1.1-1.20
		valkyrienskies: Valkyrien Skies 2 2.3.0-beta.5
		visuality: Visuality 0.7.1+1.20
		vs_clockwork: Clockwork: Create x Valkyrien Skies 1.20.1-0.1.16-fabric-b3b22e39fe
		wakes: Wakes 0.3.0+1.20.1
			com_github_jdiemke_delaunay-triangulator_delaunaytriangulator: DelaunayTriangulator 1.0.0
			satin: Satin 1.14.0
		waterdripsound: Drip Sounds 1.19-0.3.2
		waveycapes: WaveyCapes 1.4.6
		waystones: Waystones 14.1.5
		wherearemytms: Where Are My TMs? 2.1.2-hotfix
		xaerominimapfair: Xaero's Minimap 24.2.0
		xaeroworldmap: Xaero's World Map 1.39.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.20.1-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yosbr: YOSBR 0.1.2
		zoomify: Zoomify 2.13.4+1.20.1
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.5.1
			dev_isxander_settxi_settxi-core: settxi-core 2.10.6
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.6
	Loaded Shaderpack: ComplementaryReimagined_r5.1.1.zip
		Profile: Custom (+39 options changed by user)
	Flywheel Backend: Off
	Server Running: true
	Player Count: 1 / 8; [class_3222['Woelfiger'/2, l='ServerLevel[Cobbled Farms]', x=-6.85, y=64.20, z=57.45]]
	Data Packs: vanilla, fabric, file/FarmWorldSpawns, file/Any Weather Channeling v2.1.1.zip (incompatible), $polymer-resources
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: 1.20.1

**Comment by Mortycio** [comment] 2024-09-05 19:57
Me too

[crash-2024-09-05_21.54.42-server.txt](https://github.com/user-attachments/files/16899596/crash-2024-09-05_21.54.42-server.txt)

**Comment by ClientGoBoom** [comment] 2024-09-12 21:18
me too

**Comment by enbyrwolf** [comment] 2024-09-13 10:09
This issue seems to arise when the 'mons teleport to the player after a certain distance to continue following along, and only with the newest 1.20.1 version (Wakes 0.3.0+1.20.1). This issue persists even when only Cobblemon and Wakes are installed. It does not seem to matter if the 'mons were in the water in the time. Downgrading to Wakes 0.2.4+1.20.1 resolves this issue.

**Comment by Mortycio** [comment] 2024-09-13 13:16
> This issue seems to arise when the 'mons teleport to the player after a certain distance to continue following along, and only with the newest 1.20.1 version (Wakes 0.3.0+1.20.1). This issue persists even when only Cobblemon and Wakes are installed. It does not seem to matter if the 'mons were in the water in the time. Downgrading to Wakes 0.2.4+1.20.1 resolves this issue.

0.2.4 works for me, thx 👍

**Comment by NolanHewitt** [comment] 2024-09-13 16:21
This issue happens with vanilla mobs as well

**Comment by Goby56** [comment] 2024-09-14 15:13
Duplicate of #101

**Closed by Goby56** 2024-09-14 15:13 UTC
Labels: bug, crash
