### ISSUE TITLE
Ticking entity java.lang.NullPointerException

### ISSUE THREAD

**Issue by Enigmatron** [Goby56/wakes#120] opened 2024-12-03 21:43 UTC
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2024-12-03 15:17:48
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_638.method_8316(net.minecraft.class_2338)" because "net.minecraft.class_310.method_1551().field_1687" is null
	at com.goby56.wakes.simulation.WakeNode.validPos(WakeNode.java:199)
	at com.goby56.wakes.simulation.WakeHandler.insert(WakeHandler.java:76)
	at com.goby56.wakes.utils.WakesUtils.placeWakeTrail(WakesUtils.java:95)
	at net.minecraft.class_1297.spawnEffects(class_1297.java:29447)
	at net.minecraft.class_1297.handler$jha013$wakes$tick(class_1297.java:29418)
	at net.minecraft.class_1297.method_5773(class_1297.java:475)
	at net.minecraft.class_1309.method_5773(class_1309.java:2380)
	at net.minecraft.class_1308.method_5773(class_1308.java:351)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.goby56.wakes.simulation.WakeNode.validPos(WakeNode.java:199)
	at com.goby56.wakes.simulation.WakeHandler.insert(WakeHandler.java:76)
	at com.goby56.wakes.utils.WakesUtils.placeWakeTrail(WakesUtils.java:95)
	at net.minecraft.class_1297.spawnEffects(class_1297.java:29447)
	at net.minecraft.class_1297.handler$jha013$wakes$tick(class_1297.java:29418)
	at net.minecraft.class_1297.method_5773(class_1297.java:475)
	at net.minecraft.class_1309.method_5773(class_1309.java:2380)
	at net.minecraft.class_1308.method_5773(class_1308.java:351)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)

-- Entity being ticked --
Details:
	Entity Type: minecraft:chicken (net.minecraft.class_1428)
	Entity ID: 148
	Entity Name: Chicken
	Entity's Exact location: -57.59, 62.65, 110.05
	Entity's Block location: World: (-58,62,110), Section: (at 6,14,14 in -4,3,6; chunk contains blocks -64,-64,96 to -49,319,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Entity's Momentum: 0.00, -0.01, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Unknown Source)

-- Affected level --
Details:
	All players: 1 total; [class_3222['{MINECRAFT_USERNAME}'/313, l='ServerLevel[New World 2]', x=3.08, y=63.00, z=50.50]]
	Chunk stats: 3721
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,66,112), Section: (at 0,2,0 in 0,4,7; chunk contains blocks 0,-64,112 to 15,319,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 2382365 game time, 3484205 day time
	Level name: New World 2
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 164186 (now: false), thunder time: 51588 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.5, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 7740294072 bytes (7381 MiB) / 11643387904 bytes (11104 MiB) up to 36037459968 bytes (34368 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
	Identifier: Intel64 Family 6 Model 167 Stepping 1
	Microarchitecture: Rocket Lake
	Frequency (GHz): 3.50
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2414
	Graphics card #0 versionInfo: DriverVersion=32.0.15.6614
	Memory slot #0 capacity (MB): 32768.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 32768.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 79490.02
	Virtual memory used (MB): 77591.89
	Swap memory total (MB): 14064.79
	Swap memory used (MB): 298.99
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx34368M
	Fabric Mods: 
		actuallyharvest: ActuallyHarvest 1.20.1-1.1.0.9-FABRIC
		adaptive-tooltips: Adaptive Tooltips 1.3.0
		advancementinfo: AdvancementInfo 1.20-fabric0.83.0-1.4
		advancementplaques: Advancement Plaques 1.6.7
		ambientenvironment: Ambient Environment 11.0.0.1
		ambientsounds: AmbientSounds 6.1.3
		amendments: Amendments 1.20-1.2.12
		animal_feeding_trough: Animal Feeding Trough 1.1.0+1.20.1
		another_furniture: Another Furniture 1.20.1-3.0.1
		antighost: AntiGhost 1.20-fabric0.83.0-1.1.5
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		appleskin: AppleSkin 2.5.1+mc1.20
		aquamirae: Aquamirae 6
		architectury: Architectury 9.2.14
		autochefsdelight: Autochef's Delight 1.0.4+fabric
		autotag-convention: AutoTag Convention 2.0.2+1.20
			autotag: AutoTag 2.0.2+1.20
		badpackets: Bad Packets 0.4.3
		balm-fabric: Balm 7.3.9
			kuma_api: KumaAPI 20.1.8
		bcc: BetterCompatibilityChecker 4.0.1
		bettercombat: Better Combat 1.8.6+1.20.1
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0.4
			org_reflections_reflections: reflections 0.10.2
		betterf3: BetterF3 7.0.2
		betterstats: Better Statistics Screen 3.12.6+fabric-1.20.1
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.3
		betterwitchhuts: YUNG's Better Witch Huts 1.20-Fabric-3.0.3
		blur: Blur (Fabric) 3.1.0
		bobby: Bobby 5.0.1
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		capes: Capes 1.5.2+1.20
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		carryon: Carry On 2.1.2.7
		charmofundying: Charm of Undying 6.5.0+1.20.1
		chat_heads: Chat Heads 0.13.7
		chefsdelight: Chefs Delight 1.0.3-fabric-1.20.1
		cicada: CICADA 0.9.1+1.20.1
		citresewn: CIT Resewn 1.2.2+1.20.1
			citresewn-defaults: CIT Resewn: Defaults 1.2.2+1.20.1
		clickthrough: ClickThrough 1.20-fabric0.83.0-0.4.1
			gbfabrictools: GBfabrictools 1.4+1.20
		cloth-config: Cloth Config v11 11.1.136
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 12.0.0.4
		collective: Collective 7.87
		comforts: Comforts 6.4.0+1.20.1
		continuity: Continuity 3.0.0-beta.5+1.20.1
		controlling: Controlling For Fabric 12.0.2
		cratedelight: Crate Delight 24.11.22-1.20-fabric
		craterlib: CraterLib 2.1.1
		crawl: Crawl 0.12.0
			mm: Manningham Mills 2.3
		create: Create 0.5.1-j-build.1609+mc1.20.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.11-4
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.3.8+1.20.1
			porting_lib_base: Porting Lib Base 2.3.8+1.20.1
				porting_lib_gui_utils: Porting Lib Gui Utils 2.3.8+1.20.1
				porting_lib_utility: Porting Lib Utility 2.3.8+1.20.1
			porting_lib_brewing: Porting Lib Brewing 2.3.8+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.8+1.20.1
			porting_lib_entity: Porting Lib Entity 2.3.8+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.8+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.8+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.8+1.20.1
				porting_lib_common: Porting Lib Common 2.3.8+1.20.1
			porting_lib_models: Porting Lib Models 2.3.8+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.8+1.20.1
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.8+1.20.1
				porting_lib_core: Porting Lib Core 2.3.8+1.20.1
				porting_lib_model_loader: Porting Lib Model Loader 2.3.8+1.20.1
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.8+1.20.1
			porting_lib_transfer: Porting Lib Transfer 2.3.8+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.8+1.20.1
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.79-MC1.20.1
				porting_lib_tags: Porting Lib Tags 3.0
					porting_lib_gametest: Porting Lib GameTest 2.1.1090+1.20
		create_enchantment_industry: Create Enchantment Industry 1.2.16
			create_dragon_lib: Create Dragon Lib 1.4.2
		create_structures: Create: Structures 1.1.0
		createaddition: Create Crafts & Additions 1.2.4
		createdeco: Create Deco 2.0.2-1.20.1-fabric
		createfood: Create: Food 1.1.5
		creategoggles: Create Goggles 0.5.5.g
		createutilities: Create Utilities 0.3.0+1.20.1
			team_reborn_energy: Energy 3.0.0
		creativecore: CreativeCore 2.12.23
			net_minecraftforge_eventbus: eventbus 6.0.3
		ctov: ChoiceTheorem's Overhauled Village 3.4.10
		cull-less-leaves: Cull Less Leaves 1.4.2+1.21-fabric
		culturaldelights: Cultural Delights Fabric 1.0.5+1.20.1
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.1
		dark-loading-screen: Dark Loading Screen 1.6.14
		debugify: Debugify 1.20.1+2.0
		delightfulcreators: Delightful Creators 1.3-1.20.x-FDR-support
		do_a_barrel_roll: Do a Barrel Roll 3.6.1+1.20.1
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
		dynamic_fps: Dynamic FPS 3.7.6
			net_lostluma_battery: battery 1.3.0
		effective: Effective 2.3.2-1.20.1
			lodestone: Lodestone 1.20.1-1.6.2.3f-fabric
			porting_lib_blocks: Porting Lib Blocks 2.3.4+1.20.1
			porting_lib_data: Porting Lib Data 2.3.4+1.20.1
			porting_lib_items: Porting Lib Items 2.3.4+1.20.1
			porting_lib_model_generators: Porting Lib Model Generators 2.3.4+1.20.1
				porting_lib_model_materials: Porting Lib Model Materials 2.3.4+1.20.1
			satin: Satin 1.14.0
		elytratrims: Elytra Trims 3.5.4
			conditional-mixin: conditional mixin 0.6.2
		emotecraft: Emotecraft 2.2.7-b.build.50
			bendy-lib: Bendy api 4.0.0
		ends_delight: End's Delight refabricated-1.20.1-2.5
		enhancedblockentities: Enhanced Block Entities 0.9+1.20
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			spruceui: SpruceUI 5.0.0+1.20
		entity_model_features: Entity Model Features 2.2.6
		entity_texture_features: Entity Texture Features 6.2.8
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling 1.7.1
		everycomp: Every Compat 1.20-2.6.94
		expandeddelight: Expanded Delight 0.3.2
			omega-config: OmegaConfig 1.4.0+1.20.1
		explosiveenhancement: Explosive Enhancement 1.2.2-1.20.x
		extendedgears: Extended Cogwheels 2.1.1-1.20.1-0.5.1.f-fabric
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.12.3+kotlin.2.0.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
		fabricloader: Fabric Loader 0.16.5
			mixinextras: MixinExtras 0.4.1
		fabricskyboxes: FabricSkyBoxes 0.7.3+mc1.20.1
		fabrishot: Fabrishot 1.10.1
		farmersdelight: Farmer's Delight 1.20.1-2.2.2+refabricated
			porting_lib_config: Porting Lib Config 2.3.8+1.20.1
			porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.8+1.20.1
			porting_lib_loot: Porting Lib Loot 2.3.8+1.20.1
			porting_lib_recipe_book_categories: Porting Lib Recipe Book Categories 2.3.8+1.20.1
		fastquit: FastQuit 3.0.0+1.20+
		feytweaks: FeyTweaks 1.20-1.2.7
		forgeconfigapiport: Forge Config API Port 8.0.1
		geckolib: GeckoLib 4 4.4.9
			com_eliotlash_mclib_mclib: mclib 20
		geophilic: Geophilic 3.1.4
		gravestones: Gravestones v1.15
		gravestonesfix: GravestonesFix 1.0.0
		horsebuff: HorseBuff 2.1.2
		horseexpert: Horse Expert 8.1.1
		iceberg: Iceberg 1.1.25
		immediatelyfast: ImmediatelyFast 1.3.2+1.20.4
			net_lenni0451_reflect: Reflect 1.3.4
		immersive_melodies: Immersive Melodies 0.3.0+1.20.1
		indium: Indium 1.0.34+mc1.20.1
		inmis: Inmis 2.7.2-1.20.1
		inmisaddon: InmisAddon 1.0.4
		inventoryprofilesnext: Inventory Profiles Next 1.10.11
		invmove: InvMove 0.8.4
		iris: Iris 1.7.5+mc1.20.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 21
		jei: Just Enough Items 15.20.0.105
		justenoughbreeding: Just Enough Breeding 1.4.1
		kinecraft_serialization_container: Kinecraft Serialization 1.16.1
			kinecraft_serialization: Kinecraft Serialization 1.16.1
				kinecraft_serialization_1_20: Kinecraft Serialization 1.16.1
		konkrete: Konkrete 1.8.1
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		lambdynlights: LambDynamicLights 2.3.2+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
		languagereload: Language Reload 1.7.1+1.20.1
		lavender: Lavender 0.1.9+1.20
			lavender-md: lavender-md 0.1.1+1.20
			lavender-md-owo-ui: lavender-md-owo-ui 0.1.1+1.20
		leavesbegone: Leaves Be Gone 8.0.0
		libipn: libIPN 4.0.2
		lithium: Lithium 0.11.2
		lithostitched: Lithostitched 1.3.5
		loqui: Loqui 0.2.0
		make_bubbles_pop: Make Bubbles Pop 0.3.0-fabric
		melody: Melody 1.0.3
		memoryleakfix: Memory Leak Fix 1.1.5
		midnightlib: MidnightLib 1.4.1
		minecraft: Minecraft 1.20.1
		mod_sets: Mod Sets 1.10.4
			preloading_tricks: Preloading Tricks 1.2.3
				preloading_tricks_language_adapter: Preloading Tricks Dummy Language Adapter 1.2.3
			settingdust_modsets_common: common 1.10.4
			settingdust_modsets_ingame: ingame 1.10.4
		modelfix: Model Gap Fix 1.15
		modmenu: Mod Menu 7.2.2
		moonlight: Moonlight 1.20-2.13.33
		moredelight: More Delight 24.9.27-1.20-fabric
		mousetweaks: Mouse Tweaks 2.26
		mr_ctov_chefsdelightcompat: CTOV - Chef's delight Compat 2.0
		mr_ctov_createstructures: CTOV - Create: Structures 1.0
		mr_ctov_farmersdelightcompat: CTOV - Farmer Delight Compat 2.1
		mr_dungeons_andtaverns: Dungeons and Taverns 3.0.3.f
		mr_ns_crrc: Nature's Spirit - Create Recipe Compat 0.0.0
		naturalist: Naturalist 4.0.3
		natures_delight: Nature's Delight 1.6
		natures_spirit: Nature's Spirit 1.6.3-1.20.1
		nethersdelight: Nether's Delight Refabricated 1.20.1-4.1.1
		nochatreports: No Chat Reports 1.20.1-v2.2.2
		notenoughanimations: NotEnoughAnimations 1.8.1
		obscure_api: Obscure API 16
		owo: oωo 0.11.2+1.20
			blue_endless_jankson: jankson 1.2.2
		player-animator: Player Animator 1.0.2-rc1+1.20
		polymorph: Polymorph 0.49.7+1.20.1
			spectrelib: SpectreLib 0.13.17+1.20.1
		presencefootsteps: Presence Footsteps 1.10.1+1.20.1
			kirin: Kirin UI 1.15.6+1.20.1
		puzzleslib: Puzzles Lib 8.1.25
			puzzlesaccessapi: Puzzles Access Api 8.0.7
		radiantgear: Radiant Gear 2.1.6+1.20.1
		railways: Create: Steam 'n' Rails 1.6.8+fabric-mc1.20.1
		randombonemealflowers: Random Bone Meal Flowers 4.6
		recursiveresources: Recursive Resources 2.5.2+1.20
			shared-resources-api: Shared Resources API 1.5.2
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.20.1-build.101
		replaymod: Replay Mod 1.20.1-2.6.20
		resourcify: Resourcify 1.5.1
		respitecreators: Respite Creators 1.3.0-FDR
		sawmill: Universal Sawmill 1.20-1.4.3
		searchables: Searchables 1.0.3
		seasons: Fabric Seasons 2.4.2-BETA+1.20
		seasonsdelightcompat: Fabric Seasons: Delight Compat 1.0-1.3.9
		seasonsextras: Fabric Seasons: Extras 1.3.2-BETA+1.20
		shulkerboxtooltip: Shulker Box Tooltip 4.0.4+1.20.1
		silk-all: Silk (All modules) 1.10.1
			silk-commands: Silk Commands 1.10.1
			silk-core: Silk Core 1.10.1
			silk-game: Silk Game 1.10.1
			silk-igui: Silk Inventory GUI 1.10.1
			silk-nbt: Silk NBT 1.10.1
			silk-network: Silk Network 1.10.1
			silk-persistence: Silk Persistence 1.10.1
		simplyswords: Simply Swords 1.56.0-1.20.1
		skinlayers3d: 3d-Skin-Layers 1.7.2
		sliceanddice: Create Slice & Dice 3.3.1
		smallships: Small Ships 2.0.0-b1.4
		sodium: Sodium 0.5.11+mc1.20.1
		sodium-extra: Sodium Extra 0.5.4+mc1.20.1-build.115
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		sodiumdynamiclights: Sodium Dynamic Lights 1.0.9
		sodiumoptionsapi: Sodium Options API 1.0.8
			mixinsquared: MixinSquared 0.2.0-beta.6
		spark: spark 1.10.53
		spawnanimations: Spawn Animations 1.9.4+mod
		storagedelight: Storage Delight 24.9.11-1.20-fabric
		supplementaries: Supplementaries 1.20-3.1.10
		tcdcommons: TCD Commons API 3.12.3+fabric-1.20.1
		terrablender: TerraBlender 3.0.1.7
			com_electronwill_night-config_core: core 3.6.7
			com_electronwill_night-config_toml: toml 3.6.7
		things: Things 0.3.3+1.20
		treeharvester: Tree Harvester 9.1
		trinkets: Trinkets 3.7.2
		universalbonemeal: Universal Bone Meal 8.0.1
		valkyrienskies: Valkyrien Skies 2 2.3.0-beta.5
		veinminer: Veinminer 2.0.7
			de_miraculixx_core: core 2.0.7
		villagesandpillages: Villages & Pillages 1.0.2
		visuality: Visuality 0.7.1+1.20
		visualworkbench: Visual Workbench 8.0.0
		vt_downloader: VTDownloader 2.0.8+1.20.1
		wakes: Wakes 0.3.0+1.20.1
			com_github_jdiemke_delaunay-triangulator_delaunaytriangulator: DelaunayTriangulator 1.0.0
		wthit: wthit 8.15.3
		xaerominimap: Xaero's Minimap 24.6.1
		xaeroworldmap: Xaero's World Map 1.39.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.6.1+1.20.1-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yungsapi: YUNG's API 1.20-Fabric-4.0.6
			org_javassist_javassist: javassist 3.29.2-GA
		yungsbridges: YUNG's Bridges 1.20-Fabric-4.0.3
		yungsextras: YUNG's Extras 1.20-Fabric-4.0.3
		zoomify: Zoomify 2.14.2+1.20.1
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.5.2
	Loaded Shaderpack: (off)
	Flywheel Backend: GL33 Instanced Arrays
	Server Running: true
	Player Count: 1 / 8; [class_3222['{MINECRAFT_USERNAME}'/313, l='ServerLevel[New World 2]', x=3.08, y=63.00, z=50.50]]
	Data Packs: vanilla, fabric, natures_spirit:modified_jungle, natures_spirit:modified_flower_forest, lithostitched:breaks_seed_parity, natures_spirit:modified_desert, natures_spirit:modified_savannas, natures_spirit:modified_dark_forest, natures_spirit:modified_badlands, natures_spirit:modified_swamp, natures_spirit:modified_birch_forest, natures_spirit:modified_windswept_hills, natures_spirit:modified_mountain_biomes, Everycomp Generated Pack, Moonlight Mods Dynamic Assets, Supplementaries Generated Pack, Sawmill Sawmill Recipes
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: 1.20.1

**Comment by Enigmatron** [comment] 2024-12-03 21:45
this has come up a few times and prevents "smooth" saving, this issue only comes up when trying to save your world. other entities I've seen in the logs: Skeleton. I will appraise with more insight I see is valuable or is requested of me.

**Comment by pdoktor** [comment] 2024-12-04 21:06
encountering the same issue- completely breaks my modpack in terms of use.

**Comment by Enigmatron** [comment] 2024-12-05 05:32
I actually don't have that problem due to the fast save mod. I dont know if the saving would be impacted by it but your response does confirm that assumption.

**Comment by Goby56** [comment] 2024-12-29 17:43
Duplicate of #102

**Closed** 2024-12-29 17:45 UTC
Labels: bug
