### ISSUE TITLE
Water Logged Middle Mouse Select Broken

### ISSUE THREAD

**Issue by Unleashed75** [Goby56/wakes#86] opened 2024-07-12 17:55 UTC
**Describe the bug**
When using the Middle Mouse button in creative to select an item in water, it does not give the correct item.
When using the Middle Mouse button in survival to select an item in water, if you have both, the item you want it to select but also one of the items it would select in creative, it selects the wrong item.

**Expected behavior**
I expect the item I am trying to select by using the middle mouse button, to give me the item I am looking at.

**To Reproduce**
Install both Wake with Fabric.
In a new world, place a trap door in the world. With an empty hand middle mouse select it.
Now try again but with a water logged trap door.

**Screenshots**
https://github.com/user-attachments/assets/506604b8-39eb-448a-a930-5162e1f38ae4

**Hardware and OS**
If the bug is related to rendering, please provide at least which graphics card and OS you are using.

**Versions**
- Minecraft version
1.21
- Mod loader and version (e.g fabric or quilt) 
Fabric 0.15.11
- Wakes version
wakes-0.2.5+1.21
- Fabric API (or quilt equivalent) version
fabric-api-0.100.6+1.21

**Additional information**
Add any other information that could be of use here.
This seems to be related to any water logged block.

[latest.log](https://github.com/user-attachments/files/16197731/latest.log)

**Comment by Soabac** [comment] 2024-07-13 04:40
same here !! very weird

**Comment by Soabac** [comment] 2024-07-13 04:58
that's how i personnaly encountered the bug

**Comment by fl2mex** [comment] 2024-07-15 09:57
Duplicate of #82

**Closed** 2024-08-24 09:02 UTC
Labels: bug
