### ISSUE TITLE
[HUH?] Owning a dog crashes the game.

### ISSUE THREAD

**Issue by Sillylittleguy1** [Goby56/wakes#116] opened 2024-11-09 00:06 UTC
**Describe the bug**
wolfs can exist with no problem!
but when after taming one, the game completely crashes

**Expected behavior**
DOGYY

**To Reproduce**
get a dog
**Screenshots**
cant, because crash

**Hardware and OS**
win11 high-end pc

**Versions**
1.20.1
fabric
latest for 1.20.1
latest for 1.20.1

**Additional information**
i do have other mods installed, but disabling wakes fixes it

**Comment by Sillylittleguy1** [comment] 2024-11-09 01:24
oh, also throws the error: invalid tick entity

**Comment by Goby56** [comment] 2024-11-09 15:08
Can you provide the crash logs?

**Comment by Nostalgion** [comment] 2024-11-24 10:48
having this issue, produces this error when using the neruina mod which catches ticking entities instead of crashing the game.

java.lang.ClassCastException: class net.minecraft.world.entity.ai.goal.FollowOwnerGoal cannot be cast to class com.goby56.wakes.duck.ProducesWake (net.minecraft.world.entity.ai.goal.FollowOwnerGoal is in module minecraft@1.20.1 of loader 'TRANSFORMER' @7f5582db; com.goby56.wakes.duck.ProducesWake is in module wakes@0.3.01.20.1 of loader 'TRANSFORMER' @7f5582db)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.ai.goal.FollowOwnerGoal.handler$dle000$wakes$onTeleport(FollowOwnerGoal.java:517)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.ai.goal.FollowOwnerGoal.m_25303_(FollowOwnerGoal.java:143)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.ai.goal.FollowOwnerGoal.m_25313_(FollowOwnerGoal.java:126)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.ai.goal.FollowOwnerGoal.m_8037_(FollowOwnerGoal.java:113)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.ai.goal.WrappedGoal.m_8037_(WrappedGoal.java:65)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.ai.goal.GoalSelector.m_186081_(GoalSelector.java:120)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.ai.goal.GoalSelector.m_25373_(GoalSelector.java:111)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Mob.m_6140_(Mob.java:760)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2548)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Mob.m_8107_(Mob.java:536)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.AgeableMob.m_8107_(AgeableMob.java:128)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.animal.Animal.m_8107_(Animal.java:54)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.animal.Wolf.m_8107_(Wolf.java:175)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2298)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Mob.m_8119_(Mob.java:337)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.animal.Wolf.m_8119_(Wolf.java:190)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.mixinextras$bridge$accept$179(Level.java)
	at TRANSFORMER/neruina@2.1.2/com.bawnorton.neruina.handler.TickHandler.safelyTickEntities(TickHandler.java:92)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.wrapOperation$eln000$neruina$catchTickingEntities$notTheCauseOfTickLag(Level.java:9040)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.m_46653_(Level.java:479)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Goby56** [comment] 2024-11-24 19:20
Is it crashing right away or does it crash when the wolf is in water?

**Comment by Nostalgion** [comment] 2024-11-24 20:05
the error happens when the wolf teleports, but it doesnt seem to happen every time

**Comment by Sillylittleguy1** [comment] 2024-11-26 18:05
yeah, what he said^

**Comment by Goby56** [comment] 2024-12-29 17:33
Duplicate of #101

**Closed by Goby56** 2024-12-29 17:33 UTC
Labels: bug
