### ISSUE TITLE
Wakes are visible through blocks

### ISSUE THREAD

**Issue by Rasperded** [Goby56/wakes#63] opened 2024-03-30 13:35 UTC
**Describe the bug**
I can see wakrs through all blocks/entities etc. I tested this without other mods and resoursepacks but it was still visible.

**Expected behavior**
I would like to not see them XD

**To Reproduce**
Just spawned some mobs in the river and looked at them through a mountain 

**Screenshots**
![2024-03-30_17 30 05](https://github.com/Goby56/wakes/assets/138617243/5812e02b-b93e-4109-90e2-eb8af7eb33bb)
![2024-03-30_17 29 59](https://github.com/Goby56/wakes/assets/138617243/b1170621-ab9c-4c55-8bf4-10b154300e38)

**Hardware and OS**
Windows 10
(CPU) intel i5 6600

**Versions**
Minecraft version 1.20.1
Mod loader fabric and version 0.15.7
Wakes version 0.2.3
Fabric API version 0.96.11

**Additional information**
I tested this without other mods and resoursepacks but it was still visible.

**Comment by Goby56** [comment] 2024-04-03 10:38
Duplicate of #46

**Closed by Goby56** 2024-04-03 10:38 UTC
Labels: bug
