### ISSUE TITLE
Error on World gen - Entity related - Crashes to desktop. 

### ISSUE THREAD

**Issue by TheVillain-Inc** [Goby56/wakes#125] opened 2024-12-26 17:17 UTC
**Describe the bug**
On world gen, the below error is thrown, and the game crashes to desktop. It does not always happen. 

**Expected behavior**
Not crash to desktop? Or at least do it consistently ;)

**To Reproduce**
Load game world, save & exit, reload game world. 

Have tried to reproduce consistently with various mods on and off in a separate instance, no joy. 

**Screenshots**
If applicable, add screenshots to help explain the issue.

**Hardware and OS**
If the bug is related to rendering, please provide at least which graphics card and OS you are using.

**Versions**
- Minecraft version - 1.20.1
- Mod loader and version 
Forge 47.3.7 
Sinytra 1.0.0-beta.46
Fabric Forgified 0.92.2+1.11.9+1.20.1

- Wakes version 0.3.0+1.20.1
- Fabric API (or quilt equivalent) version - N/A

**Additional information**
Add any other information that could be of use here.

net.minecraft.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:897) ~[client-1.20.1-20230612.114412-srg.jar%23837!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23837!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23837!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23837!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23837!/:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.multiplayer.ClientLevel.m_6425_(net.minecraft.core.BlockPos)" because "net.minecraft.client.Minecraft.m_91087_().f_91073_" is null
	at com.goby56.wakes.simulation.WakeNode.validPos(WakeNode.java:199) ~[wakes-0.3.0+1.20.1_mapped_srg_1.20.1.jar%231490!/:?]
	at com.goby56.wakes.simulation.WakeHandler.insert(WakeHandler.java:76) ~[wakes-0.3.0+1.20.1_mapped_srg_1.20.1.jar%231490!/:?]
	at com.goby56.wakes.utils.WakesUtils.placeWakeTrail(WakesUtils.java:95) ~[wakes-0.3.0+1.20.1_mapped_srg_1.20.1.jar%231490!/:?]
	at net.minecraft.world.entity.Entity.spawnEffects(Entity.java:7707) ~[client-1.20.1-20230612.114412-srg.jar%23837!/:?]
	at net.minecraft.world.entity.Entity.handler$dfj002$wakes$tick(Entity.java:7678) ~[client-1.20.1-20230612.114412-srg.jar%23837!/:?]
	at net.minecraft.world.entity.Entity.m_8119_(Entity.java:423) ~[client-1.20.1-20230612.114412-srg.jar%23837!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2259) ~[client-1.20.1-20230612.114412-srg.jar%23837!/:?]
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:337) ~[client-1.20.1-20230612.114412-srg.jar%23837!/:?]
	at com.github.alexthe666.alexsmobs.entity.EntityElephant.m_8119_(EntityElephant.java:263) ~[alexsmobs-1.22.9.jar%23505!/:1.22.9]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[client-1.20.1-20230612.114412-srg.jar%23837!/:?]
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%23837!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[client-1.20.1-20230612.114412-srg.jar%23837!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23837!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[client-1.20.1-20230612.114412-srg.jar%23837!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23837!/:?]
	... 5 more

**Comment by Goby56** [comment] 2024-12-29 17:44
Duplicate of #102

**Comment by Goby56** [comment] 2024-12-29 17:45
Duplicate of #102

**Closed** 2024-12-29 17:45 UTC
Labels: bug
