### ISSUE TITLE
Comapt with physics mod water

### ISSUE THREAD

**Issue by sargeow** [Goby56/wakes#76] opened 2024-06-08 05:05 UTC
**Describe the bug**
wakes are stuck at normal water Y level using the pro version of the physics mod

**Expected behavior**
to follow the flow of the water

**To Reproduce**
download physics mod and wakes mod

**Screenshots**
no

**Versions**
1.20.1
quilt latest
latest 1.20.1
latest QFAPI

**Additional information**
yes

**Comment by Goby56** [comment] 2024-08-19 14:08
Duplicate of #5

**Closed by Goby56** 2024-08-19 14:08 UTC
Labels: bug
