### ISSUE TITLE
Wakes visible through blocks

### ISSUE THREAD

**Issue by Blobbon** [Goby56/wakes#47] opened 2024-01-16 16:46 UTC
![2024-01-16_17 45 23](https://github.com/Goby56/wakes/assets/92452710/5da7bda4-c570-4227-9ff6-425e3656a463)
Wakes are visible through all blocks

**Comment by Goby56** [comment] 2024-01-17 15:21
Most likely duplicate of #46

**Comment by SkightMeow** [comment] 2024-01-20 17:02
I'm having the same issue...

**Comment by Goby56** [comment] 2024-01-21 09:36
Are wakes visible through entities as well? If they are, please consider using #46 for future discussions.

**Comment by SkightMeow** [comment] 2024-01-22 06:48
> Are wakes visible through entities as well? If they are, please consider using #46 for future discussions.

Yes they are! They're visible through EVERYTHING!

**Comment by Goby56** [comment] 2024-01-27 08:23
> #46

**Closed by Goby56** 2024-01-27 08:23 UTC
Labels: bug, duplicate
